admin:
  port: 9000
supervisor:
  workers:
    - name: processbin
      replicas: 30
      exec: ./dist/processbin
      args:
        - --exit-after
        - 5
        - --log-structured
      signal_timeout: 15s
      max_restarts: 3
      startup_wait_time: 500ms
      desired_healthy_percentage: 75
      limits:
        lifespan: 4h
